heat_template_version: queens

description: External tasks definition for Skydive

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  EnableInternalTLS:
    type: boolean
    default: false
  SkydiveAnsiblePlaybook:
    type: string
    description: Path to the skydive-ansible playbook to execute
    default: /usr/share/skydive-ansible/playbook.yml.sample
  SkydiveGlobalVars:
    type: json
    description: Global Ansible variables for skydive-ansible
    default: {}
  SkydiveAnalyzerVars:
    type: json
    description: Analyzer Ansible variables for skydive-ansible
    default: {}
  SkydiveAgentVars:
    type: json
    description: Agent Ansible variables for skydive-ansible
    default: {}
  DockerSkydiveAnalyzerImage:
    description: image
    type: string
  DockerSkydiveAgentImage:
    description: image
    type: string

outputs:
  role_data:
    description: Role data for Skydive services.
    value:
      service_name: skydive_analyzer
      upgrade_tasks: []
      puppet_config:
        config_image: ''
        config_volume: ''
        step_config: ''
      docker_config: {}
      config_settings:
        tripleo.skydive_analyzer.firewall_rules:
          '150 skydive_analyzer':
            dport: 8082
            proto: tcp
      external_deploy_tasks:
        - name: skydive base step 2
          when: step == '2'
          block:
            - name: create skydive temp dirs
              file:
                path: "{{item}}"
                state: directory
              with_items:
                - "{{playbook_dir}}/skydive"

            - name: Skydive global vars fact
              set_fact:
                skydive_ansible_playbook: {get_param: SkydiveAnsiblePlaybook}
                skydive_global_vars: {get_param: SkydiveGlobalVars}
                skydive_analyzer_vars: {get_param: SkydiveAnalyzerVars}
                skydive_agent_vars: {get_param: SkydiveAgentVars}
                skydive_analyzer_docker_image: {get_param: DockerSkydiveAnalyzerImage}
                skydive_agent_docker_image: {get_param: DockerSkydiveAgentImage}

            - name: Skydive global defaults
              copy:
                dest: "{{playbook_dir}}/skydive/global_defaults.yml"
                content: |
                  skydive_docker_registry: {{skydive_analyzer_docker_image | regex_replace("([^/]*).*", "\1")}}
                  skydive_analyzer_docker_image: {{skydive_analyzer_docker_image | regex_replace("[^/]*/([^:]*).*", "\1")}}
                  skydive_analyzer_docker_image_tag: {{skydive_analyzer_docker_image | regex_replace(".*:")}}
                  skydive_analyzer_docker_command: "/usr/bin/skydive analyzer --conf /etc/skydive.yml"
                  skydive_agent_docker_image: {{skydive_agent_docker_image | regex_replace("[^/]*/([^:]*).*", "\1")}}
                  skydive_agent_docker_image_tag: {{skydive_agent_docker_image | regex_replace(".*:")}}
                  skydive_agent_docker_command: "/usr/bin/skydive agent --conf /etc/skydive.yml"
                  os_auth_url: {{overcloud_keystone_url}}
                  os_username: {{username}}
                  os_password: {{overcloud_admin_password}}
                  os_tenant)_name: {{project_name}}
                  skydive_auth_type: keystone
                  skydive_deployment_mode: container
                  skydive_flow_protocol: websocket
                  skydive_topology_probes:
                    - neutron
                    - ovsdb
                    - docker

            - name: generate Skydive global vars
              copy:
                dest: "{{playbook_dir}}/skydive/global_vars.yml"
                content: "{{skydive_global_vars|to_nice_yaml}}"

            - name: generate inventory
              copy:
                dest: "{{playbook_dir}}/skydive/inventory.yml"
                content: |
                  analyzers:
                    hosts:
                      {% for host in groups['skydive_analyzer'] -%}
                      {{hostvars.raw_get(host)['ansible_hostname']}}:
                        ansible_user: {{ hostvars.raw_get(host)['ansible_user'] | default(hostvars.raw_get(host)['ansible_ssh_user']) | default('root') }}
                        ansible_host: {{ hostvars.raw_get(host)['ansible_host'] | default(host) }}
                        ansible_become: true
                        skydive_listen_ip: {{hostvars.raw_get(host)['ctlplane_ip']}}
                        {% if skydive_analyzer_vars -%}
                        {{skydive_analyzer_vars | to_nice_yaml() | indent(6)}}
                        {%- endif %}
                      {% endfor %}

                  agents:
                    hosts:
                      {% for host in groups['skydive_agent'] -%}
                      {{hostvars.raw_get(host)['ansible_hostname']}}:
                        ansible_user: {{ hostvars.raw_get(host)['ansible_user'] | default(hostvars.raw_get(host)['ansible_ssh_user']) | default('root') }}
                        ansible_host: {{ hostvars.raw_get(host)['ansible_host'] | default(host) }}
                        ansible_become: true
                        skydive_listen_ip: {{hostvars.raw_get(host)['ctlplane_ip']}}
                        {% if skydive_agent_vars -%}
                        {{skydive_agent_vars | to_nice_yaml() | indent(6)}}
                        {%- endif %}
                      {% endfor %}

            - name: Skydive command
              set_fact:
                skydive_command: >-
                  ANSIBLE_HOST_KEY_CHECKING=False
                  ansible-playbook
                  -i '{{playbook_dir}}/skydive/inventory.yml'
                  --extra-vars '@{{playbook_dir}}/skydive/global_defaults.yml'
                  --extra-vars '@{{playbook_dir}}/skydive/global_vars.yml'
                  '{{skydive_ansible_playbook}}'
            - name: print skydive command
              debug:
                var: skydive_command
            - name: run skydive (immediate log at {{playbook_dir}}/skydive/playbook.log)
              shell: |
                {{skydive_command}} 2>&1 | tee {{playbook_dir}}/skydive/playbook.log
                exit ${PIPESTATUS[0]}
